#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCPortalE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CSCPortal")]
	public partial class CSCPortalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbCabRegistration(tbCabRegistration instance);
    partial void UpdatetbCabRegistration(tbCabRegistration instance);
    partial void DeletetbCabRegistration(tbCabRegistration instance);
    partial void InserttbEmp(tbEmp instance);
    partial void UpdatetbEmp(tbEmp instance);
    partial void DeletetbEmp(tbEmp instance);
    partial void InserttbCabRoute(tbCabRoute instance);
    partial void UpdatetbCabRoute(tbCabRoute instance);
    partial void DeletetbCabRoute(tbCabRoute instance);
    partial void InserttbCSCInitiativeTeam(tbCSCInitiativeTeam instance);
    partial void UpdatetbCSCInitiativeTeam(tbCSCInitiativeTeam instance);
    partial void DeletetbCSCInitiativeTeam(tbCSCInitiativeTeam instance);
    partial void InserttbCSCInitiative(tbCSCInitiative instance);
    partial void UpdatetbCSCInitiative(tbCSCInitiative instance);
    partial void DeletetbCSCInitiative(tbCSCInitiative instance);
    partial void InserttbEmpInCSCInitiativeTeam(tbEmpInCSCInitiativeTeam instance);
    partial void UpdatetbEmpInCSCInitiativeTeam(tbEmpInCSCInitiativeTeam instance);
    partial void DeletetbEmpInCSCInitiativeTeam(tbEmpInCSCInitiativeTeam instance);
    partial void InserttbDream(tbDream instance);
    partial void UpdatetbDream(tbDream instance);
    partial void DeletetbDream(tbDream instance);
    #endregion
		
		public CSCPortalDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CSCPortalConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSCPortalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSCPortalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSCPortalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSCPortalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbCabRegistration> tbCabRegistrations
		{
			get
			{
				return this.GetTable<tbCabRegistration>();
			}
		}
		
		public System.Data.Linq.Table<tbCabRouteLocation> tbCabRouteLocations
		{
			get
			{
				return this.GetTable<tbCabRouteLocation>();
			}
		}
		
		public System.Data.Linq.Table<tbCSCInitiativeRouteMapping> tbCSCInitiativeRouteMappings
		{
			get
			{
				return this.GetTable<tbCSCInitiativeRouteMapping>();
			}
		}
		
		public System.Data.Linq.Table<tbEmp> tbEmps
		{
			get
			{
				return this.GetTable<tbEmp>();
			}
		}
		
		public System.Data.Linq.Table<tbCabRoute> tbCabRoutes
		{
			get
			{
				return this.GetTable<tbCabRoute>();
			}
		}
		
		public System.Data.Linq.Table<tbCSCInitiativeTeam> tbCSCInitiativeTeams
		{
			get
			{
				return this.GetTable<tbCSCInitiativeTeam>();
			}
		}
		
		public System.Data.Linq.Table<tbCSCInitiative> tbCSCInitiatives
		{
			get
			{
				return this.GetTable<tbCSCInitiative>();
			}
		}
		
		public System.Data.Linq.Table<tbEmpInCSCInitiativeTeam> tbEmpInCSCInitiativeTeams
		{
			get
			{
				return this.GetTable<tbEmpInCSCInitiativeTeam>();
			}
		}
		
		public System.Data.Linq.Table<tbStatus> tbStatus
		{
			get
			{
				return this.GetTable<tbStatus>();
			}
		}
		
		public System.Data.Linq.Table<tbDream> tbDreams
		{
			get
			{
				return this.GetTable<tbDream>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCabRegistration")]
	public partial class tbCabRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CabRegistrationID;
		
		private System.Nullable<int> _CSCInitiativeID;
		
		private string _EmpID;
		
		private System.DateTime _Date;
		
		private System.Nullable<int> _CabRouteID;
		
		private System.Nullable<int> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCabRegistrationIDChanging(int value);
    partial void OnCabRegistrationIDChanged();
    partial void OnCSCInitiativeIDChanging(System.Nullable<int> value);
    partial void OnCSCInitiativeIDChanged();
    partial void OnEmpIDChanging(string value);
    partial void OnEmpIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnCabRouteIDChanging(System.Nullable<int> value);
    partial void OnCabRouteIDChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    #endregion
		
		public tbCabRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabRegistrationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CabRegistrationID
		{
			get
			{
				return this._CabRegistrationID;
			}
			set
			{
				if ((this._CabRegistrationID != value))
				{
					this.OnCabRegistrationIDChanging(value);
					this.SendPropertyChanging();
					this._CabRegistrationID = value;
					this.SendPropertyChanged("CabRegistrationID");
					this.OnCabRegistrationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeID", DbType="Int")]
		public System.Nullable<int> CSCInitiativeID
		{
			get
			{
				return this._CSCInitiativeID;
			}
			set
			{
				if ((this._CSCInitiativeID != value))
				{
					this.OnCSCInitiativeIDChanging(value);
					this.SendPropertyChanging();
					this._CSCInitiativeID = value;
					this.SendPropertyChanged("CSCInitiativeID");
					this.OnCSCInitiativeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabRouteID", DbType="Int")]
		public System.Nullable<int> CabRouteID
		{
			get
			{
				return this._CabRouteID;
			}
			set
			{
				if ((this._CabRouteID != value))
				{
					this.OnCabRouteIDChanging(value);
					this.SendPropertyChanging();
					this._CabRouteID = value;
					this.SendPropertyChanged("CabRouteID");
					this.OnCabRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCabRouteLocation")]
	public partial class tbCabRouteLocation
	{
		
		private int _RoutePointID;
		
		private string _RoutePointName;
		
		private System.Nullable<int> _CabRouteID;
		
		public tbCabRouteLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoutePointID", DbType="Int NOT NULL")]
		public int RoutePointID
		{
			get
			{
				return this._RoutePointID;
			}
			set
			{
				if ((this._RoutePointID != value))
				{
					this._RoutePointID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoutePointName", DbType="VarChar(50)")]
		public string RoutePointName
		{
			get
			{
				return this._RoutePointName;
			}
			set
			{
				if ((this._RoutePointName != value))
				{
					this._RoutePointName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabRouteID", DbType="Int")]
		public System.Nullable<int> CabRouteID
		{
			get
			{
				return this._CabRouteID;
			}
			set
			{
				if ((this._CabRouteID != value))
				{
					this._CabRouteID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCSCInitiativeRouteMapping")]
	public partial class tbCSCInitiativeRouteMapping
	{
		
		private int _CSCInitiativeID;
		
		private int _CabRouteID;
		
		public tbCSCInitiativeRouteMapping()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeID", DbType="Int NOT NULL")]
		public int CSCInitiativeID
		{
			get
			{
				return this._CSCInitiativeID;
			}
			set
			{
				if ((this._CSCInitiativeID != value))
				{
					this._CSCInitiativeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabRouteID", DbType="Int NOT NULL")]
		public int CabRouteID
		{
			get
			{
				return this._CabRouteID;
			}
			set
			{
				if ((this._CabRouteID != value))
				{
					this._CabRouteID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbEmp")]
	public partial class tbEmp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _EmpID;
		
		private string _EmpName;
		
		private string _Phone;
		
		private string _Location;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmpIDChanging(string value);
    partial void OnEmpIDChanged();
    partial void OnEmpNameChanging(string value);
    partial void OnEmpNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tbEmp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpName", DbType="VarChar(50)")]
		public string EmpName
		{
			get
			{
				return this._EmpName;
			}
			set
			{
				if ((this._EmpName != value))
				{
					this.OnEmpNameChanging(value);
					this.SendPropertyChanging();
					this._EmpName = value;
					this.SendPropertyChanged("EmpName");
					this.OnEmpNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCabRoute")]
	public partial class tbCabRoute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CabRouteID;
		
		private string _CabRouteName;
		
		private System.Nullable<int> _CSCInitiativeID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCabRouteIDChanging(int value);
    partial void OnCabRouteIDChanged();
    partial void OnCabRouteNameChanging(string value);
    partial void OnCabRouteNameChanged();
    partial void OnCSCInitiativeIDChanging(System.Nullable<int> value);
    partial void OnCSCInitiativeIDChanged();
    #endregion
		
		public tbCabRoute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabRouteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CabRouteID
		{
			get
			{
				return this._CabRouteID;
			}
			set
			{
				if ((this._CabRouteID != value))
				{
					this.OnCabRouteIDChanging(value);
					this.SendPropertyChanging();
					this._CabRouteID = value;
					this.SendPropertyChanged("CabRouteID");
					this.OnCabRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CabRouteName", DbType="VarChar(50)")]
		public string CabRouteName
		{
			get
			{
				return this._CabRouteName;
			}
			set
			{
				if ((this._CabRouteName != value))
				{
					this.OnCabRouteNameChanging(value);
					this.SendPropertyChanging();
					this._CabRouteName = value;
					this.SendPropertyChanged("CabRouteName");
					this.OnCabRouteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeID", DbType="Int")]
		public System.Nullable<int> CSCInitiativeID
		{
			get
			{
				return this._CSCInitiativeID;
			}
			set
			{
				if ((this._CSCInitiativeID != value))
				{
					this.OnCSCInitiativeIDChanging(value);
					this.SendPropertyChanging();
					this._CSCInitiativeID = value;
					this.SendPropertyChanged("CSCInitiativeID");
					this.OnCSCInitiativeIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCSCInitiativeTeam")]
	public partial class tbCSCInitiativeTeam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _CSCInitiativeID;
		
		private int _TeamID;
		
		private string _TeamName;
		
		private string _EmpID;
		
		private string _IsSPOC;
		
		private string _DLID;
		
		private string _Location;
		
		private string _HomePage;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCSCInitiativeIDChanging(System.Nullable<int> value);
    partial void OnCSCInitiativeIDChanged();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnTeamNameChanging(string value);
    partial void OnTeamNameChanged();
    partial void OnEmpIDChanging(string value);
    partial void OnEmpIDChanged();
    partial void OnIsSPOCChanging(string value);
    partial void OnIsSPOCChanged();
    partial void OnDLIDChanging(string value);
    partial void OnDLIDChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnHomePageChanging(string value);
    partial void OnHomePageChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    #endregion
		
		public tbCSCInitiativeTeam()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeID", DbType="Int")]
		public System.Nullable<int> CSCInitiativeID
		{
			get
			{
				return this._CSCInitiativeID;
			}
			set
			{
				if ((this._CSCInitiativeID != value))
				{
					this.OnCSCInitiativeIDChanging(value);
					this.SendPropertyChanging();
					this._CSCInitiativeID = value;
					this.SendPropertyChanged("CSCInitiativeID");
					this.OnCSCInitiativeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="VarChar(50)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this.OnTeamNameChanging(value);
					this.SendPropertyChanging();
					this._TeamName = value;
					this.SendPropertyChanged("TeamName");
					this.OnTeamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="VarChar(50)")]
		public string EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSPOC", DbType="VarChar(4)")]
		public string IsSPOC
		{
			get
			{
				return this._IsSPOC;
			}
			set
			{
				if ((this._IsSPOC != value))
				{
					this.OnIsSPOCChanging(value);
					this.SendPropertyChanging();
					this._IsSPOC = value;
					this.SendPropertyChanged("IsSPOC");
					this.OnIsSPOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLID", DbType="VarChar(50)")]
		public string DLID
		{
			get
			{
				return this._DLID;
			}
			set
			{
				if ((this._DLID != value))
				{
					this.OnDLIDChanging(value);
					this.SendPropertyChanging();
					this._DLID = value;
					this.SendPropertyChanged("DLID");
					this.OnDLIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePage", DbType="VarChar(200)")]
		public string HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this.OnHomePageChanging(value);
					this.SendPropertyChanging();
					this._HomePage = value;
					this.SendPropertyChanged("HomePage");
					this.OnHomePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCSCInitiative")]
	public partial class tbCSCInitiative : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CSCInitiativeID;
		
		private string _CSCInitiativeName;
		
		private System.Nullable<int> _TeamID;
		
		private string _Location;
		
		private string _DLID;
		
		private string _HomePage;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCSCInitiativeIDChanging(int value);
    partial void OnCSCInitiativeIDChanged();
    partial void OnCSCInitiativeNameChanging(string value);
    partial void OnCSCInitiativeNameChanged();
    partial void OnTeamIDChanging(System.Nullable<int> value);
    partial void OnTeamIDChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnDLIDChanging(string value);
    partial void OnDLIDChanged();
    partial void OnHomePageChanging(string value);
    partial void OnHomePageChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    #endregion
		
		public tbCSCInitiative()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CSCInitiativeID
		{
			get
			{
				return this._CSCInitiativeID;
			}
			set
			{
				if ((this._CSCInitiativeID != value))
				{
					this.OnCSCInitiativeIDChanging(value);
					this.SendPropertyChanging();
					this._CSCInitiativeID = value;
					this.SendPropertyChanged("CSCInitiativeID");
					this.OnCSCInitiativeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeName", DbType="VarChar(50)")]
		public string CSCInitiativeName
		{
			get
			{
				return this._CSCInitiativeName;
			}
			set
			{
				if ((this._CSCInitiativeName != value))
				{
					this.OnCSCInitiativeNameChanging(value);
					this.SendPropertyChanging();
					this._CSCInitiativeName = value;
					this.SendPropertyChanged("CSCInitiativeName");
					this.OnCSCInitiativeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int")]
		public System.Nullable<int> TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(50)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DLID", DbType="VarChar(50)")]
		public string DLID
		{
			get
			{
				return this._DLID;
			}
			set
			{
				if ((this._DLID != value))
				{
					this.OnDLIDChanging(value);
					this.SendPropertyChanging();
					this._DLID = value;
					this.SendPropertyChanged("DLID");
					this.OnDLIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePage", DbType="VarChar(200)")]
		public string HomePage
		{
			get
			{
				return this._HomePage;
			}
			set
			{
				if ((this._HomePage != value))
				{
					this.OnHomePageChanging(value);
					this.SendPropertyChanging();
					this._HomePage = value;
					this.SendPropertyChanged("HomePage");
					this.OnHomePageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbEmpInCSCInitiativeTeam")]
	public partial class tbEmpInCSCInitiativeTeam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeamID;
		
		private string _EmpID;
		
		private int _CSCInitiativeID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeamIDChanging(int value);
    partial void OnTeamIDChanged();
    partial void OnEmpIDChanging(string value);
    partial void OnEmpIDChanged();
    partial void OnCSCInitiativeIDChanging(int value);
    partial void OnCSCInitiativeIDChanged();
    #endregion
		
		public tbEmpInCSCInitiativeTeam()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TeamID
		{
			get
			{
				return this._TeamID;
			}
			set
			{
				if ((this._TeamID != value))
				{
					this.OnTeamIDChanging(value);
					this.SendPropertyChanging();
					this._TeamID = value;
					this.SendPropertyChanged("TeamID");
					this.OnTeamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCInitiativeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CSCInitiativeID
		{
			get
			{
				return this._CSCInitiativeID;
			}
			set
			{
				if ((this._CSCInitiativeID != value))
				{
					this.OnCSCInitiativeIDChanging(value);
					this.SendPropertyChanging();
					this._CSCInitiativeID = value;
					this.SendPropertyChanged("CSCInitiativeID");
					this.OnCSCInitiativeIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbStatus")]
	public partial class tbStatus
	{
		
		private int _STATUSID;
		
		private string _STATUSNAME;
		
		public tbStatus()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSID", DbType="Int NOT NULL")]
		public int STATUSID
		{
			get
			{
				return this._STATUSID;
			}
			set
			{
				if ((this._STATUSID != value))
				{
					this._STATUSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSNAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string STATUSNAME
		{
			get
			{
				return this._STATUSNAME;
			}
			set
			{
				if ((this._STATUSNAME != value))
				{
					this._STATUSNAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDream")]
	public partial class tbDream : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DID;
		
		private string _DTITLE;
		
		private string _DDESCRIPTION;
		
		private string _EMPID;
		
		private string _EMPNAME;
		
		private string _LOCATION;
		
		private System.Nullable<System.DateTime> _SUBMITTEDDATE;
		
		private System.Nullable<int> _STATUSID;
		
		private string _CONTACTPERSON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDIDChanging(int value);
    partial void OnDIDChanged();
    partial void OnDTITLEChanging(string value);
    partial void OnDTITLEChanged();
    partial void OnDDESCRIPTIONChanging(string value);
    partial void OnDDESCRIPTIONChanged();
    partial void OnEMPIDChanging(string value);
    partial void OnEMPIDChanged();
    partial void OnEMPNAMEChanging(string value);
    partial void OnEMPNAMEChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnSUBMITTEDDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSUBMITTEDDATEChanged();
    partial void OnSTATUSIDChanging(System.Nullable<int> value);
    partial void OnSTATUSIDChanged();
    partial void OnCONTACTPERSONChanging(string value);
    partial void OnCONTACTPERSONChanged();
    #endregion
		
		public tbDream()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DID
		{
			get
			{
				return this._DID;
			}
			set
			{
				if ((this._DID != value))
				{
					this.OnDIDChanging(value);
					this.SendPropertyChanging();
					this._DID = value;
					this.SendPropertyChanged("DID");
					this.OnDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTITLE", DbType="VarChar(100)")]
		public string DTITLE
		{
			get
			{
				return this._DTITLE;
			}
			set
			{
				if ((this._DTITLE != value))
				{
					this.OnDTITLEChanging(value);
					this.SendPropertyChanging();
					this._DTITLE = value;
					this.SendPropertyChanged("DTITLE");
					this.OnDTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DDESCRIPTION", DbType="VarChar(1000)")]
		public string DDESCRIPTION
		{
			get
			{
				return this._DDESCRIPTION;
			}
			set
			{
				if ((this._DDESCRIPTION != value))
				{
					this.OnDDESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._DDESCRIPTION = value;
					this.SendPropertyChanged("DDESCRIPTION");
					this.OnDDESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPID", DbType="VarChar(50)")]
		public string EMPID
		{
			get
			{
				return this._EMPID;
			}
			set
			{
				if ((this._EMPID != value))
				{
					this.OnEMPIDChanging(value);
					this.SendPropertyChanging();
					this._EMPID = value;
					this.SendPropertyChanged("EMPID");
					this.OnEMPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPNAME", DbType="VarChar(200)")]
		public string EMPNAME
		{
			get
			{
				return this._EMPNAME;
			}
			set
			{
				if ((this._EMPNAME != value))
				{
					this.OnEMPNAMEChanging(value);
					this.SendPropertyChanging();
					this._EMPNAME = value;
					this.SendPropertyChanged("EMPNAME");
					this.OnEMPNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(100)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBMITTEDDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SUBMITTEDDATE
		{
			get
			{
				return this._SUBMITTEDDATE;
			}
			set
			{
				if ((this._SUBMITTEDDATE != value))
				{
					this.OnSUBMITTEDDATEChanging(value);
					this.SendPropertyChanging();
					this._SUBMITTEDDATE = value;
					this.SendPropertyChanged("SUBMITTEDDATE");
					this.OnSUBMITTEDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUSID", DbType="Int")]
		public System.Nullable<int> STATUSID
		{
			get
			{
				return this._STATUSID;
			}
			set
			{
				if ((this._STATUSID != value))
				{
					this.OnSTATUSIDChanging(value);
					this.SendPropertyChanging();
					this._STATUSID = value;
					this.SendPropertyChanged("STATUSID");
					this.OnSTATUSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTPERSON", DbType="VarChar(100)")]
		public string CONTACTPERSON
		{
			get
			{
				return this._CONTACTPERSON;
			}
			set
			{
				if ((this._CONTACTPERSON != value))
				{
					this.OnCONTACTPERSONChanging(value);
					this.SendPropertyChanging();
					this._CONTACTPERSON = value;
					this.SendPropertyChanged("CONTACTPERSON");
					this.OnCONTACTPERSONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
